version: "3.9"

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "postgres"

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    depends_on: 
      - postgres
    ports:
      - 8081:80
    environment:
      PGADMIN_DEFAULT_PASSWORD: "postgres"
      PGADMIN_DEFAULT_EMAIL: "postgres@localhost.local"

  datascience:
    build: .
    image: jupyter/datascience-notebook:latest
    restart: always
    depends_on: 
      - postgres
    ports:
      - 8888:8888
